#include <SFML/Graphics.hpp>
#include <SFML/Audio.hpp>
#include <sstream>
#include "Configuration.h"
#include "Menu.h"
#include "Intro.h"
#include "Game.h"
#include "GameVariable.h"
#include "GameSelect.h"
#include "GameMatrix.h"
#include "Switch.h"
#include "Option.h"